### ISSUE TITLE
Failed to open config file: Espaper stuck on "Refreshing data" screen

### ISSUE THREAD

**Issue by schneekluth** [ThingPulse/espaper-weatherstation#12]
My Espaper Plus Kit ran fine since christmas. Yesterday, I've updated it to the latest code and now it's barely unuseable. Wifi credentials were edited in settings.h. First bootup after flashing the code works fine but on the next refresh the screen is stuck on the black "Refreshing data..." screen. Serial plotter shows the following:

```
***********set register  end**********
Failed to open config file
State: 1
Writing buffer
full init
***********set register Start**********
***********set register  end**********

About to call Weather Underground to fetch station's current data...
[HTTP] GET...
[HTTP] GET... code: 200
start document
...done.

About to call Weather Underground to fetch forcast data...
[HTTP] GET...
[HTTP] GET... code: 200
start document

```

### Expected behavior
Normal refresh of data and displaying it on the Espaper.

### Actual behavior
Stuck on "Refresh data..." screen.

### ESPaper Weather Station version
Master

### Hardware
Espaper Plus Kit

**Comment by marcelstoer** [comment]
This sounds like an issue we've been discussing with a customer on Tindie: https://discuss.tindie.com/t/epaper-kit-issue/27132/6?u=bc782c68

Did you also upgrade from ESP8266 Arduino core 2.3 to the latest 2.4.x? If so try downgrading, they apparently have a regression bug with certain APs.

**Comment by schneekluth** [comment]
Indeed, I have updated to 2.4.1. Reverting back to 2.3 fixed it. Thanks for the fast .
