### ISSUE TITLE
Bug in times under temperature graph

### ISSUE THREAD

**Issue by ptman** [ThingPulse/espaper-weatherstation#17]
### Expected behavior

Different times under the temperature graph

### Actual behavior

All the times under the temperature graph are the same. e.g. 21:00, 21:00, 21:00

### ESPaper Weather Station version

master

### Hardware

https://thingpulse.com/product/espaper-plus-kit-wifi-epaper-display/

**Comment by marcelstoer** [comment]
This actually isn't a classical bug - more a GUI that displays information in a non-obvious manner. See https://github.com/ThingPulse/espaper-weatherstation/issues/15#issuecomment-413747079 for details.

**Comment by ptman** [comment]
Thanks, it is quite unintuitive
