### ISSUE TITLE
Text of moon phase covered by temp chart

### ISSUE THREAD

**Issue by IngoDuesentrieb** [ThingPulse/espaper-weatherstation#18]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
Description of the moon phase could overlap into TempChart. E.g. German "abnehmender Halbmond". Same solution as used for drawCurrentWeather could be applied. I.e. "covering" too long text with white rectangle.
### Justification
Easy to fix, looks better.

### Workarounds
No, it's just a cosmetical improvement.

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
Maybe in this case it might be more sensible to adjust the text. Contrary to the weather description the text is under our control.

**Comment by IngoDuesentrieb** [comment]
agreed
