### ISSUE TITLE
Way to rotate display output 180º?

### ISSUE THREAD

**Issue by benguild** [ThingPulse/espaper-weatherstation#24]
### Missing feature

It'd be great to have a setting to rotate the displayed UI 180º when mounting the board upside down. So, the button hints would be at the top, but the other UI would be displayed underneath otherwise in a similar manner.

### Justification

Since the USB power input is on the right side of the board, it's occasionally necessary depending on case/installation to rotate the board upside down for this to be on the left side.

This looks fine from a hardware perspective, but the UI can't be rotated.

### Workarounds

None.

**Comment by marcelstoer** [comment]
We heard this [from elsewhere before](https://github.com/ThingPulse/espaper-client/issues/34) and noticed ourselves that such a feature would be nice to have. Depending on the aspect ratio of the display rotating by 180° would be distinctively different from rotating by 90°/270° (i.e. portrait mode).

**Comment by benguild** [comment]
Maybe if there was an enum that initially supported 0 or 1 for 0º or 180º ... then 2, 3 could be reserved for eventual portrait mode if it's ever added?

**Comment by marcelstoer** [comment]
Just for the record you _can_ rotate the whole screen but this will of course not take into account that header and footer need to be switched. This is a feature provided by our [Mini Grafx library](https://github.com/ThingPulse/minigrafx/blob/master/src/MiniGrafx.cpp#L112).

If you can live with the aforementioned shortcoming for now you can replace `gfx.setRotation(1);` in `setup()` with `gfx.setRotation(3);`.

https://github.com/ThingPulse/espaper-weatherstation/blob/9a2791383228d0df9466c06ce71bcbe08102012c/espaper-weatherstation.ino#L149

![IMG_3526](https://user-images.githubusercontent.com/624195/58585442-02ab6d00-8259-11e9-9c32-5eda744d8f12.jpg)

**Comment by benguild** [comment]
I'll give it a try soon. I'm still waiting for my programmer to show up from China, but that honestly doesn't look that bad. It seems like if the bottom row could just be switched with the top, it would probably do the trick!

**Comment by TD-er** [comment]
Nope, the reset is not software defined.
But switching the labels and moving them to the top isn't that hard in software :)
