### ISSUE TITLE
Issues with zeroing out

### ISSUE THREAD

**Issue by benguild** [ThingPulse/espaper-weatherstation#26]
### Actual behavior
This seems like potentially a parsing or API issue, but I've seen this multiple times in the past 48 hours in various formats. The main temperature will be 0º when it's hot outside, and other data is missing.

### Test code
See screenshots below.

### ESPaper Weather Station version
Latest current. I don't see any tagged release numbers on GitHub.

### Hardware
ESPaper Kit

![IMG_1775](https://user-images.githubusercontent.com/1185659/59610155-cc8a3c00-90e6-11e9-8b03-683a9c651d08.jpeg)
![IMG_8244](https://user-images.githubusercontent.com/1185659/59610156-cc8a3c00-90e6-11e9-952e-f52b167950f2.jpeg)
![IMG_8597](https://user-images.githubusercontent.com/1185659/59610157-cd22d280-90e6-11e9-8587-43fe731c31bd.jpeg)

**Comment by marcelstoer** [comment]
Always make the serial console output available please. Such behavior is normally caused by issues on the data provider side.
