### ISSUE TITLE
Wunderground Hourlies

### ISSUE THREAD

**Issue by bill-orange** [ThingPulse/espaper-weatherstation#3]
I have a question regarding espaper-weatherstation.ino.

On line 82 Wunderground instance is  WGHourly hourlies[24];

How can this possibly work?  Wunderground's Hourly JSON string reports 36 hours, numbered 0-23 MOD 24.  The streaming parser "rolls right over" the first 12 reports so the first 12 hours are always missed.  

This is not how the Wunderground's documentation describes it, but it is what I get in Orange, CA, USA.  
Here's a sample of my JSON string: https://1drv.ms/t/s!AmXKqAwyCrbxh9s58f3V3VmZQJvGfg

Perhaps something like this is needed in WundergroundHourly.cpp:

int returnFlag = 0;

void WundergroundHourly::value(String value) {
  if (returnFlag >= 24) {
  return;
  }
  if (currentKey == "hour") {
    currentHour = value.toInt();
    returnFlag++;
  }
Could Wunderground provide only 24 forecasts where you live?

Bill

**Comment by mwick83** [comment]
I also came across this issue. I addressed it in this PR: https://github.com/squix78/esp8266-weather-station/pull/91
